export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;

export const DRINKSTABLE_ID = process.env.NEXT_PUBLIC_APPWRITE_DRINKSTABLE_ID!;
export const DISHESTABLE_ID = process.env.NEXT_PUBLIC_APPWRITE_DISHESTABLE_ID!;
export const PRODUCTSTABLE_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PRODUCTSTABLE_ID!;
